#!/usr/bin/env bash

# Initialize our own variables:
proj_dir="/vagrant"
user_name="vagrant"

user_home="/home/$user_name"

# Keep the command history.
touch "$proj_dir/.bash_history"
ln -sf "$proj_dir/.bash_history" "$user_home/.bash_history"
chown --no-dereference $user_name "$proj_dir/.bash_history" "$user_home/.bash_history"

# Aptitude packages
sudo apt-add-repository -y ppa:mc3man/trusty-media

# Python 3.5
sudo add-apt-repository ppa:fkrull/deadsnakes

# MongoDB
sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 0C49F3730359A14518585931BC711F9BA15703C6
echo "deb [ arch=amd64 ] http://repo.mongodb.org/apt/ubuntu trusty/mongodb-org/3.4 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-3.4.list

sudo apt-get -y update
sudo apt-get -y install `cat $proj_dir/vm/apt-packages | egrep -v "#"`

# Python packages
# Edit /usr/bin/ipython3 to launch with python3.5
# Edit /usr/bin/pip3 to launch with python3.5
sudo cp /usr/bin/pip3 /usr/local/bin/.
sudo sed -i 's:/bin/python:/bin/python3.5:g' /usr/local/bin/pip3

sudo sed -i  -e '1s:#!/usr/bin/python3.4:#!/usr/bin/python3.5:' /usr/local/bin/ipython3

sudo pip3 install -r $proj_dir/vm/requirements

# Set Python path to yonder proejcts
export PYTHONPATH=/vagrant/:/vagrant/biyuya

sudo service mongod start